#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TabCarouselPage.Droid.Resource", IsApplication=false)]

namespace TabCarouselPage.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010005
			public static int centered = 2130771973;
			
			// aapt resource value: 0x7f01000d
			public static int clipPadding = 2130771981;
			
			// aapt resource value: 0x7f010006
			public static int fillColor = 2130771974;
			
			// aapt resource value: 0x7f01000e
			public static int footerColor = 2130771982;
			
			// aapt resource value: 0x7f010011
			public static int footerIndicatorHeight = 2130771985;
			
			// aapt resource value: 0x7f010010
			public static int footerIndicatorStyle = 2130771984;
			
			// aapt resource value: 0x7f010012
			public static int footerIndicatorUnderlinePadding = 2130771986;
			
			// aapt resource value: 0x7f01000f
			public static int footerLineHeight = 2130771983;
			
			// aapt resource value: 0x7f010013
			public static int footerPadding = 2130771987;
			
			// aapt resource value: 0x7f010008
			public static int orientation = 2130771976;
			
			// aapt resource value: 0x7f010007
			public static int pageColor = 2130771975;
			
			// aapt resource value: 0x7f010009
			public static int radius = 2130771977;
			
			// aapt resource value: 0x7f010015
			public static int selectedBold = 2130771989;
			
			// aapt resource value: 0x7f010014
			public static int selectedColor = 2130771988;
			
			// aapt resource value: 0x7f01000a
			public static int snap = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public static int strokeColor = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public static int strokeWidth = 2130771980;
			
			// aapt resource value: 0x7f010016
			public static int textColor = 2130771990;
			
			// aapt resource value: 0x7f010017
			public static int textSize = 2130771991;
			
			// aapt resource value: 0x7f010018
			public static int titlePadding = 2130771992;
			
			// aapt resource value: 0x7f010019
			public static int topPadding = 2130771993;
			
			// aapt resource value: 0x7f010000
			public static int vpiCirclePageIndicatorStyle = 2130771968;
			
			// aapt resource value: 0x7f010001
			public static int vpiIconPageIndicatorStyle = 2130771969;
			
			// aapt resource value: 0x7f010003
			public static int vpiTabPageIndicatorStyle = 2130771971;
			
			// aapt resource value: 0x7f010004
			public static int vpiTabTextStyle = 2130771972;
			
			// aapt resource value: 0x7f010002
			public static int vpiTitlePageIndicatorStyle = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f070000
			public static int default_circle_indicator_centered = 2131165184;
			
			// aapt resource value: 0x7f070001
			public static int default_circle_indicator_snap = 2131165185;
			
			// aapt resource value: 0x7f070002
			public static int default_title_indicator_selected_bold = 2131165186;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public static int colorAccent = 2131034114;
			
			// aapt resource value: 0x7f050000
			public static int colorPrimary = 2131034112;
			
			// aapt resource value: 0x7f050001
			public static int colorPrimaryDark = 2131034113;
			
			// aapt resource value: 0x7f05000c
			public static int default_circle_indicator_fill_color = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public static int default_circle_indicator_page_color = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public static int default_circle_indicator_stroke_color = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public static int default_title_indicator_footer_color = 2131034127;
			
			// aapt resource value: 0x7f050010
			public static int default_title_indicator_selected_color = 2131034128;
			
			// aapt resource value: 0x7f050011
			public static int default_title_indicator_text_color = 2131034129;
			
			// aapt resource value: 0x7f050003
			public static int psts_background_tab_pressed = 2131034115;
			
			// aapt resource value: 0x7f050004
			public static int vpi__background_holo_dark = 2131034116;
			
			// aapt resource value: 0x7f050005
			public static int vpi__background_holo_light = 2131034117;
			
			// aapt resource value: 0x7f050008
			public static int vpi__bright_foreground_disabled_holo_dark = 2131034120;
			
			// aapt resource value: 0x7f050009
			public static int vpi__bright_foreground_disabled_holo_light = 2131034121;
			
			// aapt resource value: 0x7f050006
			public static int vpi__bright_foreground_holo_dark = 2131034118;
			
			// aapt resource value: 0x7f050007
			public static int vpi__bright_foreground_holo_light = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public static int vpi__bright_foreground_inverse_holo_dark = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public static int vpi__bright_foreground_inverse_holo_light = 2131034123;
			
			// aapt resource value: 0x7f050012
			public static int vpi__dark_theme = 2131034130;
			
			// aapt resource value: 0x7f050013
			public static int vpi__light_theme = 2131034131;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f090000
			public static int default_circle_indicator_radius = 2131296256;
			
			// aapt resource value: 0x7f090001
			public static int default_circle_indicator_stroke_width = 2131296257;
			
			// aapt resource value: 0x7f090002
			public static int default_title_indicator_clip_padding = 2131296258;
			
			// aapt resource value: 0x7f090004
			public static int default_title_indicator_footer_indicator_height = 2131296260;
			
			// aapt resource value: 0x7f090005
			public static int default_title_indicator_footer_indicator_underline_padding = 2131296261;
			
			// aapt resource value: 0x7f090003
			public static int default_title_indicator_footer_line_height = 2131296259;
			
			// aapt resource value: 0x7f090006
			public static int default_title_indicator_footer_padding = 2131296262;
			
			// aapt resource value: 0x7f090007
			public static int default_title_indicator_text_size = 2131296263;
			
			// aapt resource value: 0x7f090008
			public static int default_title_indicator_title_padding = 2131296264;
			
			// aapt resource value: 0x7f090009
			public static int default_title_indicator_top_padding = 2131296265;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int vpi__tab_indicator = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int vpi__tab_selected_focused_holo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int vpi__tab_selected_holo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int vpi__tab_selected_pressed_holo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int vpi__tab_unselected_focused_holo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int vpi__tab_unselected_holo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int vpi__tab_unselected_pressed_holo = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0000
			public static int horizontal = 2131361792;
			
			// aapt resource value: 0x7f0a0002
			public static int none = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public static int triangle = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public static int underline = 2131361796;
			
			// aapt resource value: 0x7f0a0001
			public static int vertical = 2131361793;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public static int default_circle_indicator_orientation = 2131230720;
			
			// aapt resource value: 0x7f080001
			public static int default_title_indicator_footer_indicator_style = 2131230721;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int vpi__tab = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public static int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public static int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public static int MaterialFormCompat = 2131099649;
			
			// aapt resource value: 0x7f060003
			public static int MaterialFormCompat_ActionBar_TitleTextStyle = 2131099651;
			
			// aapt resource value: 0x7f060002
			public static int MaterialFormCompat_ActionBarStyle = 2131099650;
			
			// aapt resource value: 0x7f060000
			public static int MaterialFormCompat_Base = 2131099648;
			
			// aapt resource value: 0x7f06000b
			public static int TextAppearance_TabPageIndicator = 2131099659;
			
			// aapt resource value: 0x7f060004
			public static int Theme_PageIndicatorDefaults = 2131099652;
			
			// aapt resource value: 0x7f060005
			public static int Widget = 2131099653;
			
			// aapt resource value: 0x7f060006
			public static int Widget_CirclePageIndicator = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public static int Widget_IconPageIndicator = 2131099658;
			
			// aapt resource value: 0x7f060008
			public static int Widget_TabPageIndicator = 2131099656;
			
			// aapt resource value: 0x7f060009
			public static int Widget_TabPageIndicator_Text = 2131099657;
			
			// aapt resource value: 0x7f060007
			public static int Widget_TitlePageIndicator = 2131099655;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CirclePageIndicator = new int[] {
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980};
			
			// aapt resource value: 0
			public static int CirclePageIndicator_centered = 0;
			
			// aapt resource value: 1
			public static int CirclePageIndicator_fillColor = 1;
			
			// aapt resource value: 3
			public static int CirclePageIndicator_orientation = 3;
			
			// aapt resource value: 2
			public static int CirclePageIndicator_pageColor = 2;
			
			// aapt resource value: 4
			public static int CirclePageIndicator_radius = 4;
			
			// aapt resource value: 5
			public static int CirclePageIndicator_snap = 5;
			
			// aapt resource value: 6
			public static int CirclePageIndicator_strokeColor = 6;
			
			// aapt resource value: 7
			public static int CirclePageIndicator_strokeWidth = 7;
			
			public static int[] TitlePageIndicator = new int[] {
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 0
			public static int TitlePageIndicator_clipPadding = 0;
			
			// aapt resource value: 1
			public static int TitlePageIndicator_footerColor = 1;
			
			// aapt resource value: 4
			public static int TitlePageIndicator_footerIndicatorHeight = 4;
			
			// aapt resource value: 3
			public static int TitlePageIndicator_footerIndicatorStyle = 3;
			
			// aapt resource value: 5
			public static int TitlePageIndicator_footerIndicatorUnderlinePadding = 5;
			
			// aapt resource value: 2
			public static int TitlePageIndicator_footerLineHeight = 2;
			
			// aapt resource value: 6
			public static int TitlePageIndicator_footerPadding = 6;
			
			// aapt resource value: 8
			public static int TitlePageIndicator_selectedBold = 8;
			
			// aapt resource value: 7
			public static int TitlePageIndicator_selectedColor = 7;
			
			// aapt resource value: 9
			public static int TitlePageIndicator_textColor = 9;
			
			// aapt resource value: 10
			public static int TitlePageIndicator_textSize = 10;
			
			// aapt resource value: 11
			public static int TitlePageIndicator_titlePadding = 11;
			
			// aapt resource value: 12
			public static int TitlePageIndicator_topPadding = 12;
			
			public static int[] ViewPagerIndicator = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972};
			
			// aapt resource value: 0
			public static int ViewPagerIndicator_vpiCirclePageIndicatorStyle = 0;
			
			// aapt resource value: 1
			public static int ViewPagerIndicator_vpiIconPageIndicatorStyle = 1;
			
			// aapt resource value: 3
			public static int ViewPagerIndicator_vpiTabPageIndicatorStyle = 3;
			
			// aapt resource value: 4
			public static int ViewPagerIndicator_vpiTabTextStyle = 4;
			
			// aapt resource value: 2
			public static int ViewPagerIndicator_vpiTitlePageIndicatorStyle = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
