#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sample.Droid.Resource", IsApplication=true)]

namespace Sample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::TabCarouselPage.Droid.Resource.Attribute.centered = global::Sample.Droid.Resource.Attribute.centered;
			global::TabCarouselPage.Droid.Resource.Attribute.clipPadding = global::Sample.Droid.Resource.Attribute.clipPadding;
			global::TabCarouselPage.Droid.Resource.Attribute.fillColor = global::Sample.Droid.Resource.Attribute.fillColor;
			global::TabCarouselPage.Droid.Resource.Attribute.footerColor = global::Sample.Droid.Resource.Attribute.footerColor;
			global::TabCarouselPage.Droid.Resource.Attribute.footerIndicatorHeight = global::Sample.Droid.Resource.Attribute.footerIndicatorHeight;
			global::TabCarouselPage.Droid.Resource.Attribute.footerIndicatorStyle = global::Sample.Droid.Resource.Attribute.footerIndicatorStyle;
			global::TabCarouselPage.Droid.Resource.Attribute.footerIndicatorUnderlinePadding = global::Sample.Droid.Resource.Attribute.footerIndicatorUnderlinePadding;
			global::TabCarouselPage.Droid.Resource.Attribute.footerLineHeight = global::Sample.Droid.Resource.Attribute.footerLineHeight;
			global::TabCarouselPage.Droid.Resource.Attribute.footerPadding = global::Sample.Droid.Resource.Attribute.footerPadding;
			global::TabCarouselPage.Droid.Resource.Attribute.orientation = global::Sample.Droid.Resource.Attribute.orientation;
			global::TabCarouselPage.Droid.Resource.Attribute.pageColor = global::Sample.Droid.Resource.Attribute.pageColor;
			global::TabCarouselPage.Droid.Resource.Attribute.radius = global::Sample.Droid.Resource.Attribute.radius;
			global::TabCarouselPage.Droid.Resource.Attribute.selectedBold = global::Sample.Droid.Resource.Attribute.selectedBold;
			global::TabCarouselPage.Droid.Resource.Attribute.selectedColor = global::Sample.Droid.Resource.Attribute.selectedColor;
			global::TabCarouselPage.Droid.Resource.Attribute.snap = global::Sample.Droid.Resource.Attribute.snap;
			global::TabCarouselPage.Droid.Resource.Attribute.strokeColor = global::Sample.Droid.Resource.Attribute.strokeColor;
			global::TabCarouselPage.Droid.Resource.Attribute.strokeWidth = global::Sample.Droid.Resource.Attribute.strokeWidth;
			global::TabCarouselPage.Droid.Resource.Attribute.textColor = global::Sample.Droid.Resource.Attribute.textColor;
			global::TabCarouselPage.Droid.Resource.Attribute.textSize = global::Sample.Droid.Resource.Attribute.textSize;
			global::TabCarouselPage.Droid.Resource.Attribute.titlePadding = global::Sample.Droid.Resource.Attribute.titlePadding;
			global::TabCarouselPage.Droid.Resource.Attribute.topPadding = global::Sample.Droid.Resource.Attribute.topPadding;
			global::TabCarouselPage.Droid.Resource.Attribute.vpiCirclePageIndicatorStyle = global::Sample.Droid.Resource.Attribute.vpiCirclePageIndicatorStyle;
			global::TabCarouselPage.Droid.Resource.Attribute.vpiIconPageIndicatorStyle = global::Sample.Droid.Resource.Attribute.vpiIconPageIndicatorStyle;
			global::TabCarouselPage.Droid.Resource.Attribute.vpiTabPageIndicatorStyle = global::Sample.Droid.Resource.Attribute.vpiTabPageIndicatorStyle;
			global::TabCarouselPage.Droid.Resource.Attribute.vpiTabTextStyle = global::Sample.Droid.Resource.Attribute.vpiTabTextStyle;
			global::TabCarouselPage.Droid.Resource.Attribute.vpiTitlePageIndicatorStyle = global::Sample.Droid.Resource.Attribute.vpiTitlePageIndicatorStyle;
			global::TabCarouselPage.Droid.Resource.Boolean.default_circle_indicator_centered = global::Sample.Droid.Resource.Boolean.default_circle_indicator_centered;
			global::TabCarouselPage.Droid.Resource.Boolean.default_circle_indicator_snap = global::Sample.Droid.Resource.Boolean.default_circle_indicator_snap;
			global::TabCarouselPage.Droid.Resource.Boolean.default_title_indicator_selected_bold = global::Sample.Droid.Resource.Boolean.default_title_indicator_selected_bold;
			global::TabCarouselPage.Droid.Resource.Color.colorAccent = global::Sample.Droid.Resource.Color.colorAccent;
			global::TabCarouselPage.Droid.Resource.Color.colorPrimary = global::Sample.Droid.Resource.Color.colorPrimary;
			global::TabCarouselPage.Droid.Resource.Color.colorPrimaryDark = global::Sample.Droid.Resource.Color.colorPrimaryDark;
			global::TabCarouselPage.Droid.Resource.Color.default_circle_indicator_fill_color = global::Sample.Droid.Resource.Color.default_circle_indicator_fill_color;
			global::TabCarouselPage.Droid.Resource.Color.default_circle_indicator_page_color = global::Sample.Droid.Resource.Color.default_circle_indicator_page_color;
			global::TabCarouselPage.Droid.Resource.Color.default_circle_indicator_stroke_color = global::Sample.Droid.Resource.Color.default_circle_indicator_stroke_color;
			global::TabCarouselPage.Droid.Resource.Color.default_title_indicator_footer_color = global::Sample.Droid.Resource.Color.default_title_indicator_footer_color;
			global::TabCarouselPage.Droid.Resource.Color.default_title_indicator_selected_color = global::Sample.Droid.Resource.Color.default_title_indicator_selected_color;
			global::TabCarouselPage.Droid.Resource.Color.default_title_indicator_text_color = global::Sample.Droid.Resource.Color.default_title_indicator_text_color;
			global::TabCarouselPage.Droid.Resource.Color.psts_background_tab_pressed = global::Sample.Droid.Resource.Color.psts_background_tab_pressed;
			global::TabCarouselPage.Droid.Resource.Color.vpi__background_holo_dark = global::Sample.Droid.Resource.Color.vpi__background_holo_dark;
			global::TabCarouselPage.Droid.Resource.Color.vpi__background_holo_light = global::Sample.Droid.Resource.Color.vpi__background_holo_light;
			global::TabCarouselPage.Droid.Resource.Color.vpi__bright_foreground_disabled_holo_dark = global::Sample.Droid.Resource.Color.vpi__bright_foreground_disabled_holo_dark;
			global::TabCarouselPage.Droid.Resource.Color.vpi__bright_foreground_disabled_holo_light = global::Sample.Droid.Resource.Color.vpi__bright_foreground_disabled_holo_light;
			global::TabCarouselPage.Droid.Resource.Color.vpi__bright_foreground_holo_dark = global::Sample.Droid.Resource.Color.vpi__bright_foreground_holo_dark;
			global::TabCarouselPage.Droid.Resource.Color.vpi__bright_foreground_holo_light = global::Sample.Droid.Resource.Color.vpi__bright_foreground_holo_light;
			global::TabCarouselPage.Droid.Resource.Color.vpi__bright_foreground_inverse_holo_dark = global::Sample.Droid.Resource.Color.vpi__bright_foreground_inverse_holo_dark;
			global::TabCarouselPage.Droid.Resource.Color.vpi__bright_foreground_inverse_holo_light = global::Sample.Droid.Resource.Color.vpi__bright_foreground_inverse_holo_light;
			global::TabCarouselPage.Droid.Resource.Color.vpi__dark_theme = global::Sample.Droid.Resource.Color.vpi__dark_theme;
			global::TabCarouselPage.Droid.Resource.Color.vpi__light_theme = global::Sample.Droid.Resource.Color.vpi__light_theme;
			global::TabCarouselPage.Droid.Resource.Dimension.default_circle_indicator_radius = global::Sample.Droid.Resource.Dimension.default_circle_indicator_radius;
			global::TabCarouselPage.Droid.Resource.Dimension.default_circle_indicator_stroke_width = global::Sample.Droid.Resource.Dimension.default_circle_indicator_stroke_width;
			global::TabCarouselPage.Droid.Resource.Dimension.default_title_indicator_clip_padding = global::Sample.Droid.Resource.Dimension.default_title_indicator_clip_padding;
			global::TabCarouselPage.Droid.Resource.Dimension.default_title_indicator_footer_indicator_height = global::Sample.Droid.Resource.Dimension.default_title_indicator_footer_indicator_height;
			global::TabCarouselPage.Droid.Resource.Dimension.default_title_indicator_footer_indicator_underline_padding = global::Sample.Droid.Resource.Dimension.default_title_indicator_footer_indicator_underline_padding;
			global::TabCarouselPage.Droid.Resource.Dimension.default_title_indicator_footer_line_height = global::Sample.Droid.Resource.Dimension.default_title_indicator_footer_line_height;
			global::TabCarouselPage.Droid.Resource.Dimension.default_title_indicator_footer_padding = global::Sample.Droid.Resource.Dimension.default_title_indicator_footer_padding;
			global::TabCarouselPage.Droid.Resource.Dimension.default_title_indicator_text_size = global::Sample.Droid.Resource.Dimension.default_title_indicator_text_size;
			global::TabCarouselPage.Droid.Resource.Dimension.default_title_indicator_title_padding = global::Sample.Droid.Resource.Dimension.default_title_indicator_title_padding;
			global::TabCarouselPage.Droid.Resource.Dimension.default_title_indicator_top_padding = global::Sample.Droid.Resource.Dimension.default_title_indicator_top_padding;
			global::TabCarouselPage.Droid.Resource.Drawable.vpi__tab_indicator = global::Sample.Droid.Resource.Drawable.vpi__tab_indicator;
			global::TabCarouselPage.Droid.Resource.Drawable.vpi__tab_selected_focused_holo = global::Sample.Droid.Resource.Drawable.vpi__tab_selected_focused_holo;
			global::TabCarouselPage.Droid.Resource.Drawable.vpi__tab_selected_holo = global::Sample.Droid.Resource.Drawable.vpi__tab_selected_holo;
			global::TabCarouselPage.Droid.Resource.Drawable.vpi__tab_selected_pressed_holo = global::Sample.Droid.Resource.Drawable.vpi__tab_selected_pressed_holo;
			global::TabCarouselPage.Droid.Resource.Drawable.vpi__tab_unselected_focused_holo = global::Sample.Droid.Resource.Drawable.vpi__tab_unselected_focused_holo;
			global::TabCarouselPage.Droid.Resource.Drawable.vpi__tab_unselected_holo = global::Sample.Droid.Resource.Drawable.vpi__tab_unselected_holo;
			global::TabCarouselPage.Droid.Resource.Drawable.vpi__tab_unselected_pressed_holo = global::Sample.Droid.Resource.Drawable.vpi__tab_unselected_pressed_holo;
			global::TabCarouselPage.Droid.Resource.Id.horizontal = global::Sample.Droid.Resource.Id.horizontal;
			global::TabCarouselPage.Droid.Resource.Id.none = global::Sample.Droid.Resource.Id.none;
			global::TabCarouselPage.Droid.Resource.Id.triangle = global::Sample.Droid.Resource.Id.triangle;
			global::TabCarouselPage.Droid.Resource.Id.underline = global::Sample.Droid.Resource.Id.underline;
			global::TabCarouselPage.Droid.Resource.Id.vertical = global::Sample.Droid.Resource.Id.vertical;
			global::TabCarouselPage.Droid.Resource.Integer.default_circle_indicator_orientation = global::Sample.Droid.Resource.Integer.default_circle_indicator_orientation;
			global::TabCarouselPage.Droid.Resource.Integer.default_title_indicator_footer_indicator_style = global::Sample.Droid.Resource.Integer.default_title_indicator_footer_indicator_style;
			global::TabCarouselPage.Droid.Resource.Layout.vpi__tab = global::Sample.Droid.Resource.Layout.vpi__tab;
			global::TabCarouselPage.Droid.Resource.String.ApplicationName = global::Sample.Droid.Resource.String.ApplicationName;
			global::TabCarouselPage.Droid.Resource.String.Hello = global::Sample.Droid.Resource.String.Hello;
			global::TabCarouselPage.Droid.Resource.Style.MaterialFormCompat = global::Sample.Droid.Resource.Style.MaterialFormCompat;
			global::TabCarouselPage.Droid.Resource.Style.MaterialFormCompat_ActionBar_TitleTextStyle = global::Sample.Droid.Resource.Style.MaterialFormCompat_ActionBar_TitleTextStyle;
			global::TabCarouselPage.Droid.Resource.Style.MaterialFormCompat_ActionBarStyle = global::Sample.Droid.Resource.Style.MaterialFormCompat_ActionBarStyle;
			global::TabCarouselPage.Droid.Resource.Style.MaterialFormCompat_Base = global::Sample.Droid.Resource.Style.MaterialFormCompat_Base;
			global::TabCarouselPage.Droid.Resource.Style.TextAppearance_TabPageIndicator = global::Sample.Droid.Resource.Style.TextAppearance_TabPageIndicator;
			global::TabCarouselPage.Droid.Resource.Style.Theme_PageIndicatorDefaults = global::Sample.Droid.Resource.Style.Theme_PageIndicatorDefaults;
			global::TabCarouselPage.Droid.Resource.Style.Widget = global::Sample.Droid.Resource.Style.Widget;
			global::TabCarouselPage.Droid.Resource.Style.Widget_CirclePageIndicator = global::Sample.Droid.Resource.Style.Widget_CirclePageIndicator;
			global::TabCarouselPage.Droid.Resource.Style.Widget_IconPageIndicator = global::Sample.Droid.Resource.Style.Widget_IconPageIndicator;
			global::TabCarouselPage.Droid.Resource.Style.Widget_TabPageIndicator = global::Sample.Droid.Resource.Style.Widget_TabPageIndicator;
			global::TabCarouselPage.Droid.Resource.Style.Widget_TabPageIndicator_Text = global::Sample.Droid.Resource.Style.Widget_TabPageIndicator_Text;
			global::TabCarouselPage.Droid.Resource.Style.Widget_TitlePageIndicator = global::Sample.Droid.Resource.Style.Widget_TitlePageIndicator;
			global::TabCarouselPage.Droid.Resource.Styleable.CirclePageIndicator = global::Sample.Droid.Resource.Styleable.CirclePageIndicator;
			global::TabCarouselPage.Droid.Resource.Styleable.CirclePageIndicator_centered = global::Sample.Droid.Resource.Styleable.CirclePageIndicator_centered;
			global::TabCarouselPage.Droid.Resource.Styleable.CirclePageIndicator_fillColor = global::Sample.Droid.Resource.Styleable.CirclePageIndicator_fillColor;
			global::TabCarouselPage.Droid.Resource.Styleable.CirclePageIndicator_orientation = global::Sample.Droid.Resource.Styleable.CirclePageIndicator_orientation;
			global::TabCarouselPage.Droid.Resource.Styleable.CirclePageIndicator_pageColor = global::Sample.Droid.Resource.Styleable.CirclePageIndicator_pageColor;
			global::TabCarouselPage.Droid.Resource.Styleable.CirclePageIndicator_radius = global::Sample.Droid.Resource.Styleable.CirclePageIndicator_radius;
			global::TabCarouselPage.Droid.Resource.Styleable.CirclePageIndicator_snap = global::Sample.Droid.Resource.Styleable.CirclePageIndicator_snap;
			global::TabCarouselPage.Droid.Resource.Styleable.CirclePageIndicator_strokeColor = global::Sample.Droid.Resource.Styleable.CirclePageIndicator_strokeColor;
			global::TabCarouselPage.Droid.Resource.Styleable.CirclePageIndicator_strokeWidth = global::Sample.Droid.Resource.Styleable.CirclePageIndicator_strokeWidth;
			global::TabCarouselPage.Droid.Resource.Styleable.TitlePageIndicator = global::Sample.Droid.Resource.Styleable.TitlePageIndicator;
			global::TabCarouselPage.Droid.Resource.Styleable.TitlePageIndicator_clipPadding = global::Sample.Droid.Resource.Styleable.TitlePageIndicator_clipPadding;
			global::TabCarouselPage.Droid.Resource.Styleable.TitlePageIndicator_footerColor = global::Sample.Droid.Resource.Styleable.TitlePageIndicator_footerColor;
			global::TabCarouselPage.Droid.Resource.Styleable.TitlePageIndicator_footerIndicatorHeight = global::Sample.Droid.Resource.Styleable.TitlePageIndicator_footerIndicatorHeight;
			global::TabCarouselPage.Droid.Resource.Styleable.TitlePageIndicator_footerIndicatorStyle = global::Sample.Droid.Resource.Styleable.TitlePageIndicator_footerIndicatorStyle;
			global::TabCarouselPage.Droid.Resource.Styleable.TitlePageIndicator_footerIndicatorUnderlinePadding = global::Sample.Droid.Resource.Styleable.TitlePageIndicator_footerIndicatorUnderlinePadding;
			global::TabCarouselPage.Droid.Resource.Styleable.TitlePageIndicator_footerLineHeight = global::Sample.Droid.Resource.Styleable.TitlePageIndicator_footerLineHeight;
			global::TabCarouselPage.Droid.Resource.Styleable.TitlePageIndicator_footerPadding = global::Sample.Droid.Resource.Styleable.TitlePageIndicator_footerPadding;
			global::TabCarouselPage.Droid.Resource.Styleable.TitlePageIndicator_selectedBold = global::Sample.Droid.Resource.Styleable.TitlePageIndicator_selectedBold;
			global::TabCarouselPage.Droid.Resource.Styleable.TitlePageIndicator_selectedColor = global::Sample.Droid.Resource.Styleable.TitlePageIndicator_selectedColor;
			global::TabCarouselPage.Droid.Resource.Styleable.TitlePageIndicator_textColor = global::Sample.Droid.Resource.Styleable.TitlePageIndicator_textColor;
			global::TabCarouselPage.Droid.Resource.Styleable.TitlePageIndicator_textSize = global::Sample.Droid.Resource.Styleable.TitlePageIndicator_textSize;
			global::TabCarouselPage.Droid.Resource.Styleable.TitlePageIndicator_titlePadding = global::Sample.Droid.Resource.Styleable.TitlePageIndicator_titlePadding;
			global::TabCarouselPage.Droid.Resource.Styleable.TitlePageIndicator_topPadding = global::Sample.Droid.Resource.Styleable.TitlePageIndicator_topPadding;
			global::TabCarouselPage.Droid.Resource.Styleable.ViewPagerIndicator = global::Sample.Droid.Resource.Styleable.ViewPagerIndicator;
			global::TabCarouselPage.Droid.Resource.Styleable.ViewPagerIndicator_vpiCirclePageIndicatorStyle = global::Sample.Droid.Resource.Styleable.ViewPagerIndicator_vpiCirclePageIndicatorStyle;
			global::TabCarouselPage.Droid.Resource.Styleable.ViewPagerIndicator_vpiIconPageIndicatorStyle = global::Sample.Droid.Resource.Styleable.ViewPagerIndicator_vpiIconPageIndicatorStyle;
			global::TabCarouselPage.Droid.Resource.Styleable.ViewPagerIndicator_vpiTabPageIndicatorStyle = global::Sample.Droid.Resource.Styleable.ViewPagerIndicator_vpiTabPageIndicatorStyle;
			global::TabCarouselPage.Droid.Resource.Styleable.ViewPagerIndicator_vpiTabTextStyle = global::Sample.Droid.Resource.Styleable.ViewPagerIndicator_vpiTabTextStyle;
			global::TabCarouselPage.Droid.Resource.Styleable.ViewPagerIndicator_vpiTitlePageIndicatorStyle = global::Sample.Droid.Resource.Styleable.ViewPagerIndicator_vpiTitlePageIndicatorStyle;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::Sample.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::Sample.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010005
			public const int centered = 2130771973;
			
			// aapt resource value: 0x7f01000d
			public const int clipPadding = 2130771981;
			
			// aapt resource value: 0x7f010006
			public const int fillColor = 2130771974;
			
			// aapt resource value: 0x7f01000e
			public const int footerColor = 2130771982;
			
			// aapt resource value: 0x7f010011
			public const int footerIndicatorHeight = 2130771985;
			
			// aapt resource value: 0x7f010010
			public const int footerIndicatorStyle = 2130771984;
			
			// aapt resource value: 0x7f010012
			public const int footerIndicatorUnderlinePadding = 2130771986;
			
			// aapt resource value: 0x7f01000f
			public const int footerLineHeight = 2130771983;
			
			// aapt resource value: 0x7f010013
			public const int footerPadding = 2130771987;
			
			// aapt resource value: 0x7f010008
			public const int orientation = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int pageColor = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int radius = 2130771977;
			
			// aapt resource value: 0x7f010015
			public const int selectedBold = 2130771989;
			
			// aapt resource value: 0x7f010014
			public const int selectedColor = 2130771988;
			
			// aapt resource value: 0x7f01000a
			public const int snap = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int strokeColor = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int strokeWidth = 2130771980;
			
			// aapt resource value: 0x7f010016
			public const int textColor = 2130771990;
			
			// aapt resource value: 0x7f010017
			public const int textSize = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int titlePadding = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int topPadding = 2130771993;
			
			// aapt resource value: 0x7f010000
			public const int vpiCirclePageIndicatorStyle = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int vpiIconPageIndicatorStyle = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int vpiTabPageIndicatorStyle = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int vpiTabTextStyle = 2130771972;
			
			// aapt resource value: 0x7f010002
			public const int vpiTitlePageIndicatorStyle = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f070000
			public const int default_circle_indicator_centered = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int default_circle_indicator_snap = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int default_title_indicator_selected_bold = 2131165186;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int colorAccent = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int colorPrimary = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int colorPrimaryDark = 2131034113;
			
			// aapt resource value: 0x7f05000c
			public const int default_circle_indicator_fill_color = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int default_circle_indicator_page_color = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int default_circle_indicator_stroke_color = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int default_title_indicator_footer_color = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int default_title_indicator_selected_color = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int default_title_indicator_text_color = 2131034129;
			
			// aapt resource value: 0x7f050003
			public const int psts_background_tab_pressed = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int vpi__background_holo_dark = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int vpi__background_holo_light = 2131034117;
			
			// aapt resource value: 0x7f050008
			public const int vpi__bright_foreground_disabled_holo_dark = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int vpi__bright_foreground_disabled_holo_light = 2131034121;
			
			// aapt resource value: 0x7f050006
			public const int vpi__bright_foreground_holo_dark = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int vpi__bright_foreground_holo_light = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int vpi__bright_foreground_inverse_holo_dark = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int vpi__bright_foreground_inverse_holo_light = 2131034123;
			
			// aapt resource value: 0x7f050012
			public const int vpi__dark_theme = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int vpi__light_theme = 2131034131;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f090000
			public const int default_circle_indicator_radius = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int default_circle_indicator_stroke_width = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int default_title_indicator_clip_padding = 2131296258;
			
			// aapt resource value: 0x7f090004
			public const int default_title_indicator_footer_indicator_height = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int default_title_indicator_footer_indicator_underline_padding = 2131296261;
			
			// aapt resource value: 0x7f090003
			public const int default_title_indicator_footer_line_height = 2131296259;
			
			// aapt resource value: 0x7f090006
			public const int default_title_indicator_footer_padding = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int default_title_indicator_text_size = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int default_title_indicator_title_padding = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int default_title_indicator_top_padding = 2131296265;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int vpi__tab_indicator = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int vpi__tab_selected_focused_holo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int vpi__tab_selected_holo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int vpi__tab_selected_pressed_holo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int vpi__tab_unselected_focused_holo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int vpi__tab_unselected_holo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int vpi__tab_unselected_pressed_holo = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0000
			public const int horizontal = 2131361792;
			
			// aapt resource value: 0x7f0a0002
			public const int none = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int triangle = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int underline = 2131361796;
			
			// aapt resource value: 0x7f0a0001
			public const int vertical = 2131361793;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public const int default_circle_indicator_orientation = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int default_title_indicator_footer_indicator_style = 2131230721;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int vpi__tab = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int MaterialFormCompat = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int MaterialFormCompat_ActionBar_TitleTextStyle = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int MaterialFormCompat_ActionBarStyle = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int MaterialFormCompat_Base = 2131099648;
			
			// aapt resource value: 0x7f06000b
			public const int TextAppearance_TabPageIndicator = 2131099659;
			
			// aapt resource value: 0x7f060004
			public const int Theme_PageIndicatorDefaults = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int Widget = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int Widget_CirclePageIndicator = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int Widget_IconPageIndicator = 2131099658;
			
			// aapt resource value: 0x7f060008
			public const int Widget_TabPageIndicator = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int Widget_TabPageIndicator_Text = 2131099657;
			
			// aapt resource value: 0x7f060007
			public const int Widget_TitlePageIndicator = 2131099655;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CirclePageIndicator = new int[] {
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980};
			
			// aapt resource value: 0
			public const int CirclePageIndicator_centered = 0;
			
			// aapt resource value: 1
			public const int CirclePageIndicator_fillColor = 1;
			
			// aapt resource value: 3
			public const int CirclePageIndicator_orientation = 3;
			
			// aapt resource value: 2
			public const int CirclePageIndicator_pageColor = 2;
			
			// aapt resource value: 4
			public const int CirclePageIndicator_radius = 4;
			
			// aapt resource value: 5
			public const int CirclePageIndicator_snap = 5;
			
			// aapt resource value: 6
			public const int CirclePageIndicator_strokeColor = 6;
			
			// aapt resource value: 7
			public const int CirclePageIndicator_strokeWidth = 7;
			
			public static int[] TitlePageIndicator = new int[] {
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 0
			public const int TitlePageIndicator_clipPadding = 0;
			
			// aapt resource value: 1
			public const int TitlePageIndicator_footerColor = 1;
			
			// aapt resource value: 4
			public const int TitlePageIndicator_footerIndicatorHeight = 4;
			
			// aapt resource value: 3
			public const int TitlePageIndicator_footerIndicatorStyle = 3;
			
			// aapt resource value: 5
			public const int TitlePageIndicator_footerIndicatorUnderlinePadding = 5;
			
			// aapt resource value: 2
			public const int TitlePageIndicator_footerLineHeight = 2;
			
			// aapt resource value: 6
			public const int TitlePageIndicator_footerPadding = 6;
			
			// aapt resource value: 8
			public const int TitlePageIndicator_selectedBold = 8;
			
			// aapt resource value: 7
			public const int TitlePageIndicator_selectedColor = 7;
			
			// aapt resource value: 9
			public const int TitlePageIndicator_textColor = 9;
			
			// aapt resource value: 10
			public const int TitlePageIndicator_textSize = 10;
			
			// aapt resource value: 11
			public const int TitlePageIndicator_titlePadding = 11;
			
			// aapt resource value: 12
			public const int TitlePageIndicator_topPadding = 12;
			
			public static int[] ViewPagerIndicator = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972};
			
			// aapt resource value: 0
			public const int ViewPagerIndicator_vpiCirclePageIndicatorStyle = 0;
			
			// aapt resource value: 1
			public const int ViewPagerIndicator_vpiIconPageIndicatorStyle = 1;
			
			// aapt resource value: 3
			public const int ViewPagerIndicator_vpiTabPageIndicatorStyle = 3;
			
			// aapt resource value: 4
			public const int ViewPagerIndicator_vpiTabTextStyle = 4;
			
			// aapt resource value: 2
			public const int ViewPagerIndicator_vpiTitlePageIndicatorStyle = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
